# Generated by Django 3.0.8 on 2020-07-12 19:23

import awardsApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsApp', '0002_auto_20200712_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='content',
            field=awardsApp.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='design',
            field=awardsApp.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='usability',
            field=awardsApp.models.IntegerRangeField(),
        ),
    ]
