# Generated by Django 3.0.8 on 2020-07-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsApp', '0003_auto_20200712_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='voters',
        ),
    ]
