# Generated by Django 3.0.8 on 2020-07-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsApp', '0005_project_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='voters',
        ),
        migrations.AddField(
            model_name='project',
            name='voters',
            field=models.IntegerField(default=0),
        ),
    ]
